# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PSNE_sparseMat_cross <- function(NS, Poffs, expindices, combisim, ncross) {
    .Call('GPGame_PSNE_sparseMat_cross', PACKAGE = 'GPGame', NS, Poffs, expindices, combisim, ncross)
}

getPoffsCross <- function(isNash, Poffs, combisim, nsim) {
    .Call('GPGame_getPoffsCross', PACKAGE = 'GPGame', isNash, Poffs, combisim, nsim)
}

PSNE_sparseMat <- function(NS, Poffs, expindices) {
    .Call('GPGame_PSNE_sparseMat', PACKAGE = 'GPGame', NS, Poffs, expindices)
}

PSNE_sparseMat_sorted <- function(NS, Poffs, expindices) {
    .Call('GPGame_PSNE_sparseMat_sorted', PACKAGE = 'GPGame', NS, Poffs, expindices)
}

getPoffs <- function(isNash, Poffs, nsim, nobj) {
    .Call('GPGame_getPoffs', PACKAGE = 'GPGame', isNash, Poffs, nsim, nobj)
}

